# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: STS ACADEMY
# Description of the Site
description: Acadèmia de repàs GEI-Igualada
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: https://i.postimg.cc/xdbc2pvL/android-chrome-512x512.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://i.ibb.co/8YLmdHS/fons.jpg
# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: stsacademycontact@gmail.com
twitter_username: stsacademy
instagram_username: sts__academy
github_username:  stsacademy
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /
#linkedin_username: stsacademy
#facebook_username: stsacademy
#youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow



# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Hugo i Pol
# URL for the Image of the Author
author-image: https://i.postimg.cc/qqXfyBjL/e3f8cfc8-52a4-4254-9ab4-d85c14047594.jpg
# 60 Words About the Author
author-about: Som un equip d'estudiants que entenem els reptes acadèmics als quals et pots enfrontar. Ens hem unit per crear un espai on l'aprenentatge es fusiona amb l'informàtica, oferint un suport integral perquè aconsegueixis els teus objectius a la universitat.

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/polMarsol

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
